export const GITA_DATA = [
  {
    chapter: 2,
    verse: 47,
    text: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन्।',
    transliteration: 'Karmanye vadhikaras te, Ma phalesu kadachana',
    meaning: 'You have a right to perform your prescribed duty, but not to the fruits of your actions.',
  },
  {
    chapter: 2,
    verse: 27,
    text: 'जातस्य हि ध्रुवो मृत्युर्ध्रुवं जन्म मृतस्य च।',
    transliteration: 'Jatasya hi dhruvo mrityur, Dhruva janma mritasya cha',
    meaning: 'Death is certain for one who is born, and birth is certain for one who is dead.',
  },
  {
    chapter: 2,
    verse: 38,
    text: 'सुखदुःखे समे कृत्वा लाभालाभौ जयाजयौ।',
    transliteration: 'Sukha-dukhe same kritva, Labhalalabhau jayajayau',
    meaning: 'Treating pleasure and pain, gain and loss, victory and defeat as the same, wage war.',
  },
  {
    chapter: 3,
    verse: 35,
    text: 'श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात्।',
    transliteration: 'Shreyaan swadharm viguna, Para-dharmad anu-shthitad',
    meaning: 'Better to follow one\'s own dharma imperfectly than another\'s dharma perfectly.',
  },
  {
    chapter: 4,
    verse: 38,
    text: 'न हि ज्ञानेन सदृशं पवित्रमिह विद्यते।',
    transliteration: 'Na hi jnanem sade rishaan, Pavitra miha vidyate',
    meaning: 'There is nothing as purifying as knowledge in this world.',
  },
  {
    chapter: 5,
    verse: 23,
    text: 'शक्नोत्यहैव यः सोढुं प्राक्शरीरविमोक्षणात्।',
    transliteration: 'Shaknoty-aheva yaha, Sodhu praksharira vimoksanat',
    meaning: 'One who can tolerate the urges of the mind and senses is firmly established.',
  },
  {
    chapter: 6,
    verse: 26,
    text: 'यतो यतो निश्चरति मनश्चञ्चलमस्थिरम्।',
    transliteration: 'Yato yato nischarati, Mana-nchalam asthiram',
    meaning: 'The mind is restless and unsteady, but practice and detachment can steady it.',
  },
  {
    chapter: 7,
    verse: 26,
    text: 'वेदाहं समतीतानि वर्तमानानि चार्जुन।',
    transliteration: 'Vedaham samatitani, Vartamanu charjun',
    meaning: 'I know all beings past, present, and future, yet none know me fully.',
  },
  {
    chapter: 10,
    verse: 10,
    text: 'तेषां सतत-युक्तानां भजतां प्रीति-पूर्वकम्।',
    transliteration: 'Tesham sata-yuktanam, Bhajatam priti-purvakam',
    meaning: 'To those who are constantly devoted and engaged in worshipping me, I give them wisdom.',
  },
  {
    chapter: 12,
    verse: 13,
    text: 'अद्वेष्टा सर्वभूतानां मैत्रः करुण एव च।',
    transliteration: 'Adveshta sarvabhutanam, Maitraha karuna eva cha',
    meaning: 'One who is free from hatred toward all beings and is friendly and compassionate.',
  },
];
